// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJt1p16VTaWsRguhZ60OBjdcjQiEVnJU8',
    appId: '1:1087618510894:web:f096c20099663df1742fbf',
    messagingSenderId: '1087618510894',
    projectId: 'petnest-75483',
    authDomain: 'petnest-75483.firebaseapp.com',
    storageBucket: 'petnest-75483.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeqs3jeLicfoo6YCfEscFkDAkI07KkXCc',
    appId: '1:1087618510894:ios:4a6c5ca4b88104bf742fbf',
    messagingSenderId: '1087618510894',
    projectId: 'petnest-75483',
    storageBucket: 'petnest-75483.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeqs3jeLicfoo6YCfEscFkDAkI07KkXCc',
    appId: '1:1087618510894:ios:4a6c5ca4b88104bf742fbf',
    messagingSenderId: '1087618510894',
    projectId: 'petnest-75483',
    storageBucket: 'petnest-75483.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJt1p16VTaWsRguhZ60OBjdcjQiEVnJU8',
    appId: '1:1087618510894:web:634ee47c13cf7114742fbf',
    messagingSenderId: '1087618510894',
    projectId: 'petnest-75483',
    authDomain: 'petnest-75483.firebaseapp.com',
    storageBucket: 'petnest-75483.firebasestorage.app',
  );
}
